---
- hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull surajiiitb/ecommercefrontend:latest



    - name: Run Docker container
      shell: docker run -d -p 3000:80 surajiiitb/ecommercefrontend:latest