---
- hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull surajiiitb/ecommercebackend:latest



    - name: Run Docker container
      shell: docker run -d -p 8081:8080 surajiiitb/ecommercebackend:latest