apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend-deployment
  labels:
    app: ecommerce-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
        - name: ecommerce-backend
          image: surajiiitb/ecommercebackend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-db-config
                  key: DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-db-config
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-db-config
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-db-config
                  key: HIBERNATE_DIALECT
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-db-config
                  key: DDL_AUTO

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service
spec:
  type: LoadBalancer
  selector:
    app: ecommerce-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31222
