apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend-deployment
  labels:
    app: ecommerce-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
        - name: ecommerce-frontend
          image: surajiiitb/ecommercefrontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-backend-config
                  key: BACKEND_HOST
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-backend-config
                  key: BACKEND_PORT

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-service
spec:
  type: NodePort
  selector:
    app: ecommerce-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32207
