---
- name: Deploy Ecommerce app to minikube
  hosts: all
  tasks:
    - name: apply secret
      shell: ../k8s-deploy/kubectl apply -f db-deployment-service.yml
    - name: apply secret2
      shell: ../k8s-deploy/kubectl apply -f db-config.yml

    - name: apply backend
      shell: ../k8s-deploy/kubectl apply -f backend-deployment-service.yml

    - name: apply backend1
      shell: ../k8s-deploy/kubectl apply -f backend-config.yml

    - name: apply frontend
      shell: ../k8s-deploy/kubectl apply -f frontend-deployment-service.yml

    # - name: apply elasticsearch
    #   shell: kubectl apply -f ../kubernetes-config/elasticsearch.yaml

    # - name: apply logstash
    #   shell: kubectl apply -f ../kubernetes-config/logstash.yaml

    # - name: apply kibana
    #   shell: kubectl apply -f ../kubernetes-config/kibana.yaml

    # - name: apply filebeat
    #   shell: kubectl apply -f ../kubernetes-config/filebeat.yaml
